### ISSUE TITLE
CustomerEnquiryTC 

### ISSUE THREAD

**Issue by deepthi-t** [nikhildas/AutomationWrapper#31]
**Methods:**
verifyCustomerEnquiry
verifyAdjustment
verifySericeChargeAccount
verifyServiceProducts

Clicking on element 'By.xpath: //tr[@id='customerSearchForm:customerSearchFBTabSet:0:customerSearchResults_row_0']'
ERROR : UAVOIDABLE ERROR OCCURED."

**Comment by nikhildas** [comment]
Fixed Issue
