### ISSUE TITLE
TC_63 Verify Create a credit limit and a call monitor limit for a new customer

### ISSUE THREAD

**Issue by Lakshmi-Mallu** [nikhildas/AutomationWrapper#34]
Exchange & Number area is not getting selected using script in Service Details screen. Getting "No such element found" error in Eclipse Console.

ServiceProvisioningTC	newCustomerPCLCreditLimit

**Comment by nikhildas** [comment]
Fixed.
Handled availability of invisible 'Deallocated' command button
