### ISSUE TITLE
TC_65 Verify PEL+PDL Service Provisioning - New Customer

### ISSUE THREAD

**Issue by Lakshmi-Mallu** [nikhildas/AutomationWrapper#36]
Not clicking on "Yes" button on the popup (Do you want provide a Broadband service on the same service order). PDL provisioning not processing along with PEL

ServiceProvisioningTC	newCustomerPELandPDL

**Comment by nikhildas** [comment]
Fixed.
Handled availability of invisible 'Deallocated' command button
